projects:

  # Basic configuration
  - name: lachee.dev                            # Name of the project
    project: /var/www/html/lachee.dev/          # CWD of the proeject
    config: ./git-deploy.yaml                   # Relative path of the configuration
    secret: ASj2w@jn@NJFK                       # The API key for the API and webhooks
    providers:                                  # List of providers allowed to use this 
      - github
      - azure
      - api
    webhook: https://discord.gg/token/          # URL to the discord webhook to publish build information
    env:                                        # Enviroment Variables to set before build. These will override the configuration enviromental variables.
      PROFILE_IMAGE: https://i.lu.je/2021/chrome_7Lh9OShqhJ.png 

  # Configuration via SSH
  - name: xve
    ssh:                                                      # When SSH is given, GitDeploy will establish a connection to the project directory on the remote
      host: 192.168.1.12                                      # Host address
      user: lachee                                            # Host user
      key:  /home/USER/.ssh/id_xve                            # SSH key used to login
    secret: ASj2w@jn@NJFK                                     # The API key for the API and webhooks
    project: /home/USER/xve/                                  # CWD of the project
    config: ./git-deploy.yaml                                 # Relative path of the configuration

  # # Basic configuration, showing that the config can be objects too
  # - name: lachee.dev
  #   config: 
  #     deploys:
  #     - name: master
  #       env:
  #       setup: npm i
  #       build: ./build.sh
  #       post: 




# Example configuration
deploys:
  # Define a new group, with the name master
  - name: website
    
    # The branches it can deploy to
    branches: [ master ]
    
    # The enviroment variables it can deploy to
    env:
      MODE: production
      HIDE_SKILLS: true
      HIDE_PLATFORMS: true
    
    # pre and post commands
    pre:
    post:

    # The deployer and its settings
    use: npm
    with:
      script: build
      project: some_project



# Additional Example Deployers
# Runs a script to build
use: script
with: 
  script: ./build.sh # Script to build

# Runs a script
use: ./build.sh

# Runs composer build
use: composer
with: 
  script: build # Optional: name of the composer script to run

# Runs NPM build
use: npm
with: 
  script: build # Optional: name of the NPM script to run

# Runs dotnet projects
use: dotnet
with: 
  project: some_project # Name of the project to build

# Runs a docker project
use: docker
with:
  # TODO: Figure out how to run a docker container